### ISSUE TITLE
Unsubscribe before server returns the subscription id

### ISSUE THREAD

**Issue by chengyin** [absinthe-graphql/absinthe-socket#11]
Let's say I have a component with the following lifecycle events:

```js
componentDidMount() {
  this.unsubscribe = this.props.subscribe();
}

componentWillUnmount() {
  this.unsubscribe();
}
```

In certain cases this component may be mounted and unmounted quickly (dropdown menu on hover, or dialogs that get dismissed instantly). This may lead to the situation where `subscriptionId` hasn't been returned from the server before `this.unsubscribe` is called.

With Absinthe, this will generate a server side error.

I don't think there is any API enables the component itself to avoid such situation. Should absinthe-socket handle this?

**Comment by mgtitimoli** [comment]
Hi @chengyin,

Just to confirm, are you using absinthe-socket or any of the connector packages?

**Comment by chengyin** [comment]
Actually let me emphasize that I’m not 100% sure if the quick unmounting is causing subscription id missing. But that’s one way to reproduce the issue. 

And we are using the absinthe Apollo link.

**Comment by mgtitimoli** [comment]
If you are using @absinthe/socket-apollo-link, then this should be handled automatically ([here](https://github.com/absinthe-graphql/absinthe-socket/blob/master/packages/socket-apollo-link/src/createAbsintheSocketLink.js#L32)).

Where did you see the error?

**Comment by chengyin** [comment]
Sorry, this was an issue on our end. I updated to the newest version of absinthe link in our master branch but I was testing on a branch with older version.

With the new version I hasn't seen any issues yet.

Sorry about the false report!

**Comment by mgtitimoli** [comment]
Great @chengyin, np, cheers.
