### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by English3000** [absinthe-graphql/absinthe-socket#21]
[Repo](https://github.com/English3000/Elixir/tree/master/Phoenix/Absinthe/hackernews)

```js
require.register("@absinthe/socket-relay/src/index.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "@absinthe/socket-relay");
  (function() {
    // @flow

// @create-index

export {default as createFetcher} from "./createFetcher.js";
export {default as createSubscriber} from "./createSubscriber.js";
export {default as isSubscribed} from "./isSubscribed.js";
  })();
});
```

Literally copied & pasted `environment.js` & `absinthe.js` code from "Craft GraphQL APIs in Elixir with Absinthe" source code.

In the book, they put the frontend in a separate repo.

**Comment by English3000** [comment]
Update: I got my app to render by commenting out my entire `environment.js`

```js
// import { createFetcher, createSubscriber } from "@absinthe/socket-relay";
// import { Environment, Network, RecordSource, Store } from "relay-runtime";
// import absintheSocket from "./absinthe";
//
// export default new Environment({ network: Network.create( createFetcher(absintheSocket),
//                                                           createSubscriber(absintheSocket) ),
//                                  store: new Store(new RecordSource()) });
```

Also, `react-router-native` has the same issue. From what I've gleaned through searches, the issue may have to do with Babel 6 not transpiling the `import` statements nested within functions..?

Regardless, I still need a fix so I can use `createFetcher` and `createSubscriber`

**Comment by English3000** [comment]
Tried

```js
const createFetcher = require("@absinthe/socket-relay").createFetcher;
const createSubscriber = require("@absinthe/socket-relay").createSubscriber;
```

Doesn't work

**Comment by English3000** [comment]
In Google Chrome, the error (for this exact same issue) is

Uncaught SyntaxError: Unexpected token export

**Comment by English3000** [comment]
To the best of my knowledge, this issue is being caused by how `babel-brunch` compiles your `/src/index.js`

I have opened an issue with them: https://github.com/babel/babel-brunch/issues/66

**Comment by mgtitimoli** [comment]
I guess the issue you are experiencing is because of this [line](https://github.com/absinthe-graphql/absinthe-socket/blob/master/packages/socket-relay/package.json#L6), there it should point to `"compat/cjs/index.js"` as the other packages...

Don't you mind trying to import from `@absinthe/socket-relay/compat/cjs`, and tell me how it went?

**Comment by English3000** [comment]
IT WORKED!!!!!

**Comment by mgtitimoli** [comment]
Great @English3000!

I will add this to task I need to acomplish for the next release, thanks for having taken the time to report this!

Happy coding!
