### ISSUE TITLE
Does not resubscribe on reconnect

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe-socket#22]
It seems that absinthe-socket is not resubscribing on reconnect if the websocket connection is interrupted.

Steps to reproduce:

1. Boot an absinthe server locally
2. Open a web page with absinthe-socket that successfully connects and subscribes
3. Ctrl-C the web server
4. Boot the web server again
5. Observe that the websocket reconnects, but the client does not re-subscribe any subscriptions

**Comment by rmoorman** [comment]
@samphilipd, I just tried the same with the example application from the Craft GraphQL APIs in Elixir with Absinthe book and it does actually resubscribe.

Could you share an example application that reproduces the error? (with recent versions of the related packages)

**Comment by mgtitimoli** [comment]
Hey there!

I've just release v0.2.0, this should be working (it should have worked before too), if not, feel free to open the issue with a repo to test.
