### ISSUE TITLE
Any way to stop requests on connection close?

### ISSUE THREAD

**Issue by paintingwithcode** [absinthe-graphql/absinthe-socket#24]
Hi, we're using sockets as our transport layer to connect to our Absinthe Schema on the server. We have an authentication module setup where if valid tokens aren't passed in to the socket params we deny the connection and attempt to close by returning an `:error` in the Phoenix Socket connect function.

The client acknowledges this error and does log a `connection: closed` error but this does not stop AbsintheSocket from retrying the failed query or mutation endlessly without time outs.

Is there any way to force stop the module or abort the requests?

**Comment by mgtitimoli** [comment]
Hey there!

I've just released v0.2.0 and I certainly believe this should not be happening right now, if it does, just reopen the issue and I will figure out what's going on.

Thanks!

**Comment by gorkunov** [comment]
seems it still there

**Comment by astroTANSAN** [comment]
This seems to still be an issue
