### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by namxam** [absinthe-graphql/absinthe-socket#32]
Sorry for raising this as an issue, but I think this is actually one.

We haven't seen any updates for almost a year. And there are critical bugs which are fixed in form of unmerged pull requests.

I know open source work is difficult, but there are people offering help, but none of the maintainers is responding. It would be great if we could get some kind of feedback.

**Comment by mgtitimoli** [comment]
https://github.com/absinthe-graphql/absinthe-socket/commit/d4fccc7f2d29d719e2c8d73ac157008da79ae559
