### ISSUE TITLE
Using native Javascript WebSockets

### ISSUE THREAD

**Issue by MarbilleJuntado** [absinthe-graphql/absinthe-socket#35]
Is there a way to use the [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) object instead of `phoenix.js`'s `Socket` as an argument to `withinAbsintheSocket.create/1`?

**Comment by benwilson512** [comment]
If you write your own server websocket handler sure. There wouldn't really be any point in using this library at that point though.
