### ISSUE TITLE
Also working on WS link

### ISSUE THREAD

**Issue by bjunc** [absinthe-graphql/absinthe-socket#4]
Hey guys,

I just pushed a websocket link for Apollo 2.0, and when I checked NPM to ensure it published, I saw your lib!  Seems like we're working on similar things, not sure if it'd make sense for me to help you guys out, merge code, etc..  Thought I'd throw it out there.

Here's the repo: [PhoenixWebSocketLink](https://github.com/bjunc/apollo-link-phx-ws).

**Comment by tlvenn** [comment]
Hey @bjunc,

Interesting timing ;) We have now released our JS integration with support for Apollo Link and Relay. We definitely welcome your feedback if you get a chance to either look at our code or use our Apollo Link.

You can find a good overview of the general direction of our lib in the [readme section](https://github.com/absinthe-graphql/absinthe-socket/blob/master/packages/socket/README.md#features) of the core project.

If you have questions on our approach or supported features, please let us know as well.
