### ISSUE TITLE
The correct way to `cancel`

### ISSUE THREAD

**Issue by rafbgarcia** [absinthe-graphql/absinthe-socket#5]
I managed to successfully cancel my subscription from a channel, however the way I did it doesn't feel the proper way.

```js
stopReceivingOrders() {
    this.absintheSocket = AbsintheSocket.cancel(this.absintheSocket, this.absintheSocket.notifiers[0])
}
```

Before that I was trying to `cancel` using a `this.notifier` attr:

```js
startReceivingOrders() {
  this.notifier = AbsintheSocket.send(this.absintheSocket, {
    operation: this.subscriptionGraph(),
    variables: {}
  })

  AbsintheSocket.observe(this.absintheSocket, this.notifier, {
    onAbort: this.onAbort.bind(this),
    onError: this.onError.bind(this),
    onCancel: this.onCancel.bind(this),
    onStart: this.onStart.bind(this),
    onResult: this.onResult.bind(this),
  })
}

stopReceivingOrders() {
  this.absintheSocket = AbsintheSocket.cancel(this.absintheSocket, this.notifier)
}
```

However in this case `this.notifier.subscriptionId` is `undefined`, hence having it fail on the server side.

Is this the way to go or am I missing something on the socket setup?

Thanks

**Comment by mgtitimoli** [comment]
The latest version of notifier is passed to observers in the `onStart` handler, this one contains **subscriptionId** with the value returned from the server, so you should store it, and only cancel after having receiving this.

**Comment by mgtitimoli** [comment]
We might add a way in the future to cancel in the meantime that is exactly the case you have.

This could set a flag in the notifier, so if it's true at the time subscription is established, then an unsubscribe is sent and notifier is removed once we get the ack from the server.

**Comment by rafbgarcia** [comment]
Here you mean? It's coming back empty though.

<img width="862" alt="pedidos" src="https://user-images.githubusercontent.com/1904314/32579070-c741b5d6-c4c6-11e7-87bb-66ac13226614.png">

I can even receive messages after that point

<img width="752" alt="pedidos" src="https://user-images.githubusercontent.com/1904314/32579237-50460a26-c4c7-11e7-8480-085a61d8ed45.png">

**Comment by mgtitimoli** [comment]
You are right, the updated notifier is not passed but the old one ([here](https://github.com/absinthe-graphql/absinthe-socket/blob/master/packages/socket/src/pushRequest.js#L28)).

I will fix this and release a new version.
