### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by idkjs** [absinthe-graphql/absinthe-socket#54]
Are there docs explaining the use case for these packages? For example, when it makes sense to use this. 

Thank you for sharing this package.

**Comment by samantadearaujo** [comment]
I didn't understand your question.

**Comment by tlvenn** [comment]
If you have a JS client that uses subscriptions, you will need those packages or roll your own. Absinthe is leveraging Phoenix channels to handle subscriptions and as such you need a corresponding client built on top of Phoenix JS channel that follows the convention / protocol used by Absinthe.
