### ISSUE TITLE
Uncaught TypeError: Cannot instantiate an arrow function

### ISSUE THREAD

**Issue by Hermanverschooten** [absinthe-graphql/absinthe-socket#59]
When using `parcel v2`, or `esbuild` the generated JS code, causes the above error when calling `AbsintheSocket.create`.

I was after some trial and error able to make it working again for `esbuild` by using `require` instead of `import`.

```elixir
// import * as AbsintheSocket from "@absinthe/socket";
const AbsintheSocket = require('@absinthe/socket');
```

This did not work with `parcel` however.

I cloned José Valim's esbuild test repo to replicate the error, https://github.com/Hermanverschooten/phx_esbuild_demo, branch `test_absinthe`

**Comment by neurodynamic** [comment]
I'm also seeing this issue.

@Hermanverschooten Your `require` fix works for me; thanks for posting it!

**Comment by neurodynamic** [comment]
@Hermanverschooten Shot in the dark, but you wouldn't have any idea why using [esbuild's inject feature](https://esbuild.github.io/api/#inject) might cause this bug to come back even if you're using the `require` trick, would you? I'm at a loss.

**Comment by Hermanverschooten** [comment]
@neurodynamic No I am sorry, no clue. Sorry about the delay, I was traveling. But if you find out, please share.

**Comment by Hermanverschooten** [comment]
I gave up on `Parcel` long time ago and since moving to the `esbuild` hex package and using the `require` solution I have had no more issues.

**Comment by RichMatthews** [comment]
I'm still seeing this issue. even with the require method. I'm using `@absinthe/socket-apollo-link` version `0.2.1`. `phoenix` version `1.7.1`. Anything else I need to do?

**Comment by Hermanverschooten** [comment]
@RichMatthews  I am still using the require method, I must say my phoenix is still at 1.6.15 for that project.
